serverless:
  component: "@sls-next/serverless-component@latest"

custom:
  secrets: ${file(secrets.json)}
  usertableName: "users-table-new-2"
  logtableName: "logs-table"
  historyTableName: "history-table"

service: serverless-jwt-authorizer
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  versionFunctions: false
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    AWS_ID: ${self:custom.secrets.AWS_ID}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "lambda:InvokeFunction"
      Resource: 
        - "arn:aws:dynamodb:us-east-1:${self:custom.secrets.AWS_ID}:table/${self:custom.usertableName}"
        - "arn:aws:dynamodb:us-east-1:${self:custom.secrets.AWS_ID}:table/${self:custom.logtableName}"
        - "arn:aws:dynamodb:us-east-1:${self:custom.secrets.AWS_ID}:table/${self:custom.historyTableName}"
        - "arn:aws:lambda:us-east-1:*:*"
functions:
  login:
    handler: pages/api/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  register:
    handler: pages/api/reg.handler
    events:
      - http:
          path: register
          method: post
          cors: true
  docupload:
    handler: pages/api/docupload.handler
    events:
      - http:
          path: docupload
          method: post
          cors: true
  authorize:
    handler: pages/api/authorize.handler
    events:
      - http:
          path: authorize
          method: post
          cors: true
  dummyportal:
    handler: pages/api/dummyportal.handler
    events:
      - http:
          path: dummyportal
          method: post
          cors: true
  imageProcessing:
    handler : pages/api/imageProcessing.handler
    events:
      - http:
          path: imageProcessing
          method: post
          cors: true
  pollDB:
    handler : pages/api/poll.handler
    events:
      - http:
          path: pollDB
          method: post
          cors: true
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usertableName}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    logsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.logtableName}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    historyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.historyTableName}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    